id: P81FA3288
initial_creation_type: input
source_metadata:
  title: Ngulchu Dharmabhadra Series
  language: bo
  description: 'A series of texts by and about the great Gelugpa scholar Ngulchu Dharmabhadra
    (dngul chu dharma bhadra, 1771–1852):'
  volume:
    9bf940565bb048c9b9ae01b7dc1d5940:
      title: Method of Confession based on the Four Powers
      parent: Confession
    89b3f38303eb445c8f04c1e594fb9721:
      title: Concise Explanatory Outline of the Heart of Wisdom
      parent: Prajñāpāramitā
created_at: '2022-03-01T01:02:04.201562'
last_modified_at: '2022-03-01T01:02:04.201565'
